# Generated by Django 4.2.3 on 2023-07-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('USD', 'usd'), ('UZS', 'uzs'), ('RUB', 'rub'), ('EUR', 'eur')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
