# Generated by Django 4.2.3 on 2023-07-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_wallet_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
