# Generated by Django 4.2.3 on 2023-08-18 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_wallet_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['-created_at']},
        ),
    ]
