# Generated by Django 4.2.3 on 2023-08-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='token',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
