# Generated by Django 4.2.3 on 2023-07-07 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_rename_price_moneyitem_amount_alter_moneyitem_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymoney',
            name='description',
        ),
        migrations.RemoveField(
            model_name='money',
            name='target_time',
        ),
        migrations.RemoveField(
            model_name='repeatmoney',
            name='money',
        ),
        migrations.AddField(
            model_name='money',
            name='repeat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='money.repeatmoney'),
        ),
        migrations.AlterField(
            model_name='repeatmoney',
            name='repeat',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('no repeat', 'No Repeat')], max_length=100),
        ),
    ]
