# Generated by Django 4.2.3 on 2023-07-10 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_money_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyitem',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
