# Generated by Django 4.2.3 on 2023-07-11 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_remove_money_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='currency',
            field=models.CharField(choices=[('USD', 'usd'), ('UZS', 'uzs'), ('RUB', 'rub'), ('EUR', 'eur')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moneyitem',
            name='money',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_item', to='money.money'),
        ),
    ]
