# Generated by Django 4.2.3 on 2023-07-11 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0008_remove_money_category_money_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='name',
        ),
    ]
