# Generated by Django 4.2.3 on 2023-07-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0009_remove_money_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='name',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
