# Generated by Django 4.2.3 on 2023-07-12 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0010_money_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyitem',
            name='money',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='money_item', to='money.money'),
        ),
    ]
