# Generated by Django 4.2.3 on 2023-07-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0012_alter_moneyitem_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneyitem',
            name='name',
        ),
    ]
