# Generated by Django 4.2.3 on 2023-08-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0015_autopay'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopay',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
