# Generated by Django 4.2.3 on 2023-08-17 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0016_autopay_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autopay',
            name='processed',
        ),
        migrations.AddField(
            model_name='autopay',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='money.moneyitem'),
        ),
    ]
