# Generated by Django 4.2.3 on 2023-08-17 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0017_remove_autopay_processed_autopay_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autopay',
            name='transaction',
        ),
    ]
