# Generated by Django 4.2.3 on 2023-08-18 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0018_remove_autopay_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopay',
            name='money',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_pay', to='money.money'),
        ),
    ]
