# Generated by Django 4.2.3 on 2023-08-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0022_money_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopay',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
