# Generated by Django 4.2.3 on 2023-08-25 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0024_money_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyitem',
            name='money',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_item', to='money.money'),
        ),
    ]
