# Generated by Django 4.2.3 on 2023-09-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0025_alter_moneyitem_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='target_money',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='moneyitem',
            name='amount',
            field=models.FloatField(),
        ),
    ]
