# Generated by Django 4.2.3 on 2023-09-13 08:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_exitsession_exit_time'),
        ('money', '0027_qarz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('amount', models.IntegerField(default=0)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_amount', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('money', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt', to='money.money')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.wallet')),
            ],
        ),
        migrations.DeleteModel(
            name='Qarz',
        ),
    ]
