# Generated by Django 4.2.3 on 2023-09-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0028_debt_delete_qarz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
