# Generated by Django 4.2.3 on 2023-09-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0030_alter_debt_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
