# Generated by Django 4.2.3 on 2023-09-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0031_alter_debt_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='is_debt',
            field=models.BooleanField(default=False),
        ),
    ]
